# path to Panoptic-CUDAL dataset, no tailing path seperator!
dataset_dir: "/home/devuser/workspace/data/Panoptic-CUDAL"
dataset_name: "Panoptic-CUDAL"

model_settings: {
  # Defines model backbone architecture
  # Baseline model. type: str. options: SalsaNext | Reichert | SalsaNextAdf
    baseline: "Reichert", 
  # Backbone architecture
    model_type: "efficientnet_v2_l",
  # Loss function. type: str. options: Tversky | CE | Lovasz | Dirichlet | SalsaNextAdf
    loss_function: "Dirichlet",
  # Model Layer settings
  ## toggle attention block. type: bool
    attention: true,
  ## inject meta data at multiple scales. type: bool
    multi_scale_meta: true,
  
  # Define what optional input channel types are used
    # range (1 channel) and xyz (3 channels) are always considered -> min.4 channels
  ## toggle use of normals as input (+3 extra channels). type: bool
    normals: true,
  ## toggle use of reflectivity as input (+1 extra channels). type: bool
    reflectivity: true,

  # AUGMENTATIONS
  ## rotation augmentation. type: bool
    rotate: false,   
  ## flip augmentation. type: bool
    flip: true,
  
  # Toggle use of Dropout at inference
  use_mc_sampling: true,
  mc_samples:  50,

  ## Image projection resolution
    projection: [128, 1024],
  
  # GENERAL SETTINGS
  ## path to pretrained model weights, if no pretrained option is desired set to pretrained: null
    ## type: str or null (NoneType), no tailing path seperator! expects .pt or .pth file
    pretrained: null, #"/home/devuser/workspace/data/Training_SemanticSegmentation/train_semanticKitti/Reichert/test_split_0008/efficientnet_v2_l_anmDirichlet/25-08-22_13-59-48/best_epoch_000094.pt", #"/home/devuser/workspace/data/Training_SemanticSegmentation/train_semanticKitti/Reichert/test_split_0008/efficientnet_v2_l_anmDirichlet/25-08-22_13-59-48/best_epoch_000054.pt" #"/home/devuser/workspace/data/Training_SemanticSegmentation/train_semanticKitti/SalsaNext/test_split_0008/efficientnet_v2_l_anmTversky/25-07-17_12-55-47/model_final.pt"
    # SalsaNext: "/home/devuser/workspace/data/Training_SemanticSegmentation/train_semanticKitti/SalsaNext/test_split_0008/efficientnet_v2_l_anmTversky/25-07-17_12-55-47/model_final.pt"
    # Reichert Dirchlet: "/home/devuser/workspace/data/train_semantic_THAB_v3/test_split_final/efficientnet_v2_l_anmpDirichlet/25-07-01_17-13-35/model_000001.pt"
    # Reichert pretrained: "/home/devuser/workspace/data/train_semantic_THAB_v3/efficientnet_v2_l_anmpTversky/model_final.pth"
}

model_weights: {
  Dirichlet: {
    w_ls:    0.25,   # add only if you want extra IoU (on softmax probs)
    w_nll:   1.0,  # Dirichlet-categorical NLL or density based
    w_imax:  3.5,   # 2.0
    w_dce:   0.0,   # 1.0
    w_kl:    0.8,  # KL evidence term governs alpha0, keeps near prior_concentration
    w_ir:    0.0,  # information regularization term, keeps off-class near 1
    w_comp:  3.0    # shapes uncertainty on unsure pixels
  },
  SalsaNext: {
    w_nll:   1.0, 
    w_ls:    1.0
  },
  Tversky: {
    w_ce:         1.0, 
    w_tversky:    1.0
  }
}

train_params: {
  ## learning rate for training
    learning_rate: 1.e-3,
  ## Sets batch size for training
    batch_size: 4,
  ## Sets numbor of worker processes
    num_workers: 4,
  ## Sets number of total training epochs
    num_epochs: 100,
  ## Sets weight decay
  weight_decay: 1.e-4,
  ## Gradually/Linearilly increases learning rate until base learning is reached for 'num_warmup_epochs' Epochs
  num_warmup_epochs: 2

}

logging_settings: {
  ## Test ID of the test sequence for the leave one out CV. -1 for training on all
    test_id: 8,
  ## Sets interval to test every nth epoch
    test_every_nth_epoch: 2,
  ## Sets interval to save model weights every nth epoch. -1 for saving only last epoch
    save_every_nth_epoch: 2,
  ## path to log directory
    log_dir: "/home/devuser/workspace/data/Training_SemanticSegmentation/train_Panoptic-CUDAL",
    metrics: {
      McConfEmpAcc: false, # bool, MC Mean Confidence vs. Empirical Most-Likely Accuracy Reliability Plot
      EntErrRel: false, # bool, entropy error reliability diagram, plots at which entropy levels the model's uncertainty matches its true error frequency
      IouPlt: true
    }
}